name: Webserv CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t webserv .

      - name: Run tests inside container
        run: docker run --rm webserv test

  clang-tidy-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install clang-tidy
        run: sudo apt-get update && sudo apt-get install -y clang-tidy

      - name: Install bear for compilation database
        run: sudo apt-get install -y bear

      - name: Generate Compilation Database
        run: bear -- make -j$(nproc)

      - name: Run clang-tidy
        run: find ../ -name '*.cpp' | xargs clang-tidy -p .
        # -warnings-as-errors='*'

  dast-scan:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      # - run: docker build -t webserv .
      - run: docker run -d -p 8080:8080 --name webserv webserv dast
      - run: sleep 5
      - uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:8080'
          failAction: true
          config: 'failThreshold=Medium'
          reportFile: 'zap_report.html'
      - uses: actions/upload-artifact@v4
        with:
          name: ZAP-Dast-Report
          path: zap_report.html
